import { createClient } from '@supabase/supabase-js'
import type { JsonValue } from '@/lib/jobs/types'
import { EXPORT_FORMATS, EXPORT_RESOURCES, type ExportFormat, type ExportResource } from './types'

type Payload={exportId:string;organizationId:string;resource:ExportResource;format:ExportFormat}
const esc=(v:unknown)=>{const s=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
const xml=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();const key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error('Missing Supabase service-role configuration.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function parse(payload:JsonValue):Payload{if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Invalid export payload.');const p=payload as Record<string,unknown>;if(typeof p.exportId!=='string'||typeof p.organizationId!=='string'||!EXPORT_RESOURCES.includes(p.resource as ExportResource)||!EXPORT_FORMATS.includes(p.format as ExportFormat))throw new Error('Invalid export payload.');return p as Payload}
function csv(rows:Record<string,unknown>[]){const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];return Buffer.from([cols.join(','),...rows.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\n'),'utf8')}
function excel(rows:Record<string,unknown>[]){const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const row=(values:unknown[])=>`<Row>${values.map(v=>`<Cell><Data ss:Type="String">${xml(v)}</Data></Cell>`).join('')}</Row>`;const body=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Export"><Table>${row(cols)}${rows.map(r=>row(cols.map(c=>r[c]))).join('')}</Table></Worksheet></Workbook>`;return Buffer.from(body,'utf8')}
function pdf(rows:Record<string,unknown>[]){const lines=['Flowtix Export',...rows.slice(0,1000).map(r=>Object.entries(r).map(([k,v])=>`${k}: ${String(v??'')}`).join(' | '))];const safe=lines.map(l=>l.replace(/[()\\]/g,'\\$&').slice(0,180));let content='BT /F1 9 Tf 36 800 Td ';let y=0;for(const line of safe){if(y&&y%48===0)content+='ET ';content+=`(${line}) Tj 0 -14 Td `;y++}content+='ET';const objs=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let out='%PDF-1.4\n';const offsets:number[]=[];for(let i=1;i<objs.length;i++){offsets[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=Buffer.byteLength(out);out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer << /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out,'binary')}
export async function processExport(payload:JsonValue){const p=parse(payload);const supabase=client();await supabase.from('export_jobs').update({status:'processing',started_at:new Date().toISOString(),error_message:null}).eq('id',p.exportId).eq('organization_id',p.organizationId);const {data,error}=await supabase.from(p.resource).select('*').eq('organization_id',p.organizationId).limit(50000);if(error)throw new Error(`Unable to read export data: ${error.message}`);const rows=(data??[]) as Record<string,unknown>[];const ext=p.format==='excel'?'xls':p.format;const mime=p.format==='csv'?'text/csv':p.format==='excel'?'application/vnd.ms-excel':'application/pdf';const bytes=p.format==='csv'?csv(rows):p.format==='excel'?excel(rows):pdf(rows);const path=`${p.organizationId}/${p.exportId}.${ext}`;const upload=await supabase.storage.from('exports').upload(path,bytes,{contentType:mime,upsert:true});if(upload.error)throw new Error(`Unable to store export: ${upload.error.message}`);const completed=new Date();const {error:updateError}=await supabase.from('export_jobs').update({status:'completed',storage_bucket:'exports',storage_path:path,file_name:`${p.resource}-${completed.toISOString().slice(0,10)}.${ext}`,mime_type:mime,row_count:rows.length,file_size_bytes:bytes.length,completed_at:completed.toISOString(),expires_at:new Date(completed.getTime()+30*86400000).toISOString()}).eq('id',p.exportId).eq('organization_id',p.organizationId);if(updateError)throw new Error(`Unable to finalize export: ${updateError.message}`);return {exportId:p.exportId,rowCount:rows.length,fileSizeBytes:bytes.length}}
