import { requirePermission } from '@/lib/auth'
import { enqueueJob } from '@/lib/jobs/queue'
import { createClient } from '@/lib/supabase/server'
import { EXPORT_FORMATS, EXPORT_RESOURCES, type CreateExportInput, type CreateExportScheduleInput, type ExportJobRecord, type ExportScheduleRecord } from './types'
const mapJob=(r:Record<string,unknown>):ExportJobRecord=>({id:String(r.id),organizationId:String(r.organization_id),resource:r.resource as ExportJobRecord['resource'],format:r.format as ExportJobRecord['format'],status:r.status as ExportJobRecord['status'],fileName:r.file_name?String(r.file_name):null,rowCount:Number(r.row_count??0),fileSizeBytes:Number(r.file_size_bytes??0),createdAt:String(r.created_at),completedAt:r.completed_at?String(r.completed_at):null,expiresAt:r.expires_at?String(r.expires_at):null,errorMessage:r.error_message?String(r.error_message):null,createdBy:String(r.created_by)})
const mapSchedule=(r:Record<string,unknown>):ExportScheduleRecord=>({id:String(r.id),organizationId:String(r.organization_id),name:String(r.name),resource:r.resource as ExportScheduleRecord['resource'],format:r.format as ExportScheduleRecord['format'],frequency:r.frequency as ExportScheduleRecord['frequency'],timezone:String(r.timezone),nextRunAt:String(r.next_run_at),isActive:Boolean(r.is_active),filters:(r.filters&&typeof r.filters==='object'?r.filters:{}) as Record<string,unknown>,createdAt:String(r.created_at),updatedAt:String(r.updated_at)})
function validate(input:CreateExportInput){if(!EXPORT_RESOURCES.includes(input.resource))throw new Error('Unsupported export resource.');if(!EXPORT_FORMATS.includes(input.format))throw new Error('Unsupported export format.')}
export async function listExports(){const m=await requirePermission('reports.export');const s=await createClient();const {data,error}=await s.from('export_jobs').select('*').eq('organization_id',m.organization_id).order('created_at',{ascending:false}).limit(100);if(error)throw new Error(error.message);return (data??[]).map(r=>mapJob(r as Record<string,unknown>))}
export async function createExport(input:CreateExportInput){validate(input);const m=await requirePermission('reports.export');const s=await createClient();const {data,error}=await s.from('export_jobs').insert({organization_id:m.organization_id,resource:input.resource,format:input.format,filters:input.filters??{},status:'queued',created_by:m.user_id}).select('*').single();if(error)throw new Error(error.message);const record=mapJob(data as Record<string,unknown>);const job=await enqueueJob({organizationId:m.organization_id,queue:'reports',jobType:'exports.generate',payload:{exportId:record.id,organizationId:m.organization_id,resource:input.resource,format:input.format},idempotencyKey:`export:${record.id}`,maxAttempts:5});await s.from('export_jobs').update({background_job_id:job.id}).eq('id',record.id).eq('organization_id',m.organization_id);return record}
export async function getExportDownload(id:string){const m=await requirePermission('reports.export');const s=await createClient();const {data,error}=await s.from('export_jobs').select('*').eq('id',id).eq('organization_id',m.organization_id).single();if(error)throw new Error('Export not found.');if(data.status!=='completed'||!data.storage_path)throw new Error('Export is not ready.');const signed=await s.storage.from(data.storage_bucket||'exports').createSignedUrl(data.storage_path,300,{download:data.file_name||true});if(signed.error)throw new Error(signed.error.message);return signed.data.signedUrl}
export async function listExportSchedules(){const m=await requirePermission('reports.export');const s=await createClient();const {data,error}=await s.from('export_schedules').select('*').eq('organization_id',m.organization_id).order('created_at',{ascending:false});if(error)throw new Error(error.message);return (data??[]).map(r=>mapSchedule(r as Record<string,unknown>))}
export async function createExportSchedule(input:CreateExportScheduleInput){validate(input);const m=await requirePermission('reports.export');const s=await createClient();const {data,error}=await s.from('export_schedules').insert({organization_id:m.organization_id,name:input.name.trim(),resource:input.resource,format:input.format,frequency:input.frequency,timezone:input.timezone??'Asia/Manila',next_run_at:input.nextRunAt,is_active:input.isActive??true,filters:input.filters??{},created_by:m.user_id}).select('*').single();if(error)throw new Error(error.message);return mapSchedule(data as Record<string,unknown>)}
export async function deleteExportSchedule(id:string){const m=await requirePermission('reports.export');const s=await createClient();const {error}=await s.from('export_schedules').delete().eq('id',id).eq('organization_id',m.organization_id);if(error)throw new Error(error.message)}
