import { requirePermission } from '@/lib/auth'
import { normalizeReportRange, type ReportRange } from '@/lib/reports'
import { createClient } from '@/lib/supabase/server'
import type { AIAnalyticsOverview, AIAnalyticsSnapshot, AIDimensionMetric, AITrendPoint } from './types'

type Row = Record<string, unknown>
type StoredRow = { id:string; period:ReportRange; period_start:string; period_end:string; captured_at:string; total_requests:number|string; completed_requests:number|string; failed_requests:number|string; cancelled_requests:number|string; input_tokens:number|string; output_tokens:number|string; total_tokens:number|string; cost_micros:number|string; average_latency_ms:number|string; success_rate:number|string; conversations:number|string; assistant_messages:number|string; summaries:number|string; sentiment_analyses:number|string; coaching_analyses:number|string; transcript_runs:number|string; feature_metrics:unknown; prompt_metrics:unknown; model_metrics:unknown; provider_metrics:unknown; trend_metrics:unknown; metadata:unknown }
const n=(v:unknown):number=>Number.isFinite(Number(v))?Number(v):0
const s=(v:unknown):string=>typeof v==='string'?v:''
const arr=<T>(v:unknown):T[]=>Array.isArray(v)?v as T[]:[]
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{}
const pct=(a:number,b:number):number=>b>0?a/b*100:0
const days=(p:ReportRange):number=>p==='7d'?7:p==='90d'?90:p==='365d'?365:30
function map(row:StoredRow):AIAnalyticsSnapshot{return{id:row.id,period:row.period,periodStart:row.period_start,periodEnd:row.period_end,capturedAt:row.captured_at,totalRequests:n(row.total_requests),completedRequests:n(row.completed_requests),failedRequests:n(row.failed_requests),cancelledRequests:n(row.cancelled_requests),inputTokens:n(row.input_tokens),outputTokens:n(row.output_tokens),totalTokens:n(row.total_tokens),costMicros:n(row.cost_micros),averageLatencyMs:n(row.average_latency_ms),successRate:n(row.success_rate),conversations:n(row.conversations),assistantMessages:n(row.assistant_messages),summaries:n(row.summaries),sentimentAnalyses:n(row.sentiment_analyses),coachingAnalyses:n(row.coaching_analyses),transcriptRuns:n(row.transcript_runs),featureAdoption:arr<AIDimensionMetric>(row.feature_metrics),promptMetrics:arr<AIDimensionMetric>(row.prompt_metrics),modelMetrics:arr<AIDimensionMetric>(row.model_metrics),providerMetrics:arr<AIDimensionMetric>(row.provider_metrics),trend:arr<AITrendPoint>(row.trend_metrics),metadata:obj(row.metadata)}}
function dimension(rows:Row[],keyOf:(r:Row)=>string):AIDimensionMetric[]{const groups=new Map<string,Row[]>();for(const row of rows){const key=keyOf(row)||'unknown';groups.set(key,[...(groups.get(key)??[]),row])}return [...groups].map(([key,items])=>{const completed=items.filter(r=>s(r.status)==='completed').length;const failed=items.filter(r=>s(r.status)==='failed').length;const lat=items.map(r=>n(r.latency_ms)).filter(Boolean);return{key,label:key.replaceAll('_',' '),requests:items.length,completed,failed,inputTokens:items.reduce((a,r)=>a+n(r.input_tokens),0),outputTokens:items.reduce((a,r)=>a+n(r.output_tokens),0),costMicros:items.reduce((a,r)=>a+n(r.cost_micros),0),averageLatencyMs:lat.length?lat.reduce((a,b)=>a+b,0)/lat.length:0,successRate:pct(completed,completed+failed)}}).sort((a,b)=>b.requests-a.requests)}
function trend(period:ReportRange,end:Date,usage:Row[]):AITrendPoint[]{const length=days(period);const fmt=new Intl.DateTimeFormat('en',{month:'short',day:'numeric'});return Array.from({length},(_,i)=>{const d=new Date(end);d.setUTCDate(end.getUTCDate()-(length-i-1));const date=d.toISOString().slice(0,10);const items=usage.filter(r=>s(r.created_at).slice(0,10)===date);const lat=items.map(r=>n(r.latency_ms)).filter(Boolean);return{date,label:fmt.format(d),requests:items.length,completed:items.filter(r=>s(r.status)==='completed').length,failed:items.filter(r=>s(r.status)==='failed').length,tokens:items.reduce((a,r)=>a+n(r.input_tokens)+n(r.output_tokens),0),costMicros:items.reduce((a,r)=>a+n(r.cost_micros),0),averageLatencyMs:lat.length?lat.reduce((a,b)=>a+b,0)/lat.length:0}})}
export function normalizeAIAnalyticsPeriod(value:string|undefined):ReportRange{return normalizeReportRange(value)}
export async function collectAIAnalyticsSnapshot(period:ReportRange):Promise<AIAnalyticsSnapshot>{const membership=await requirePermission('reports.view');const supabase=await createClient();const organizationId=membership.organization_id;const now=new Date();const start=new Date(now);start.setUTCDate(now.getUTCDate()-days(period)+1);start.setUTCHours(0,0,0,0);const from=start.toISOString(),to=now.toISOString();const [usageR,convR,msgR,sumR,sentR,coachR,transR]=await Promise.all([
 supabase.from('ai_usage_reservations').select('feature,status,provider,model,input_tokens,output_tokens,cost_micros,latency_ms,metadata,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('ai_conversations').select('id,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('ai_messages').select('role,prompt_key,provider,model,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('summaries').select('id,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('ai_sentiment_analyses').select('id,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('ai_coaching_analyses').select('id,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
 supabase.from('ai_transcript_processing_runs').select('id,status,created_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
]);const results=[usageR,convR,msgR,sumR,sentR,coachR,transR];const error=results.find(r=>r.error)?.error;if(error)throw new Error(`Unable to collect AI analytics: ${error.message}`);const usage=(usageR.data??[]) as Row[];const messages=(msgR.data??[]) as Row[];const completed=usage.filter(r=>s(r.status)==='completed').length;const failed=usage.filter(r=>s(r.status)==='failed').length;const lat=usage.map(r=>n(r.latency_ms)).filter(Boolean);const input=usage.reduce((a,r)=>a+n(r.input_tokens),0),output=usage.reduce((a,r)=>a+n(r.output_tokens),0);const promptByUsage=usage.map(r=>({...r,prompt_key:s(obj(r.metadata).prompt_key)||s(obj(r.metadata).promptKey)||'unspecified'}));const payload={organization_id:organizationId,period,period_start:from,period_end:to,total_requests:usage.length,completed_requests:completed,failed_requests:failed,cancelled_requests:usage.filter(r=>s(r.status)==='cancelled').length,input_tokens:input,output_tokens:output,total_tokens:input+output,cost_micros:usage.reduce((a,r)=>a+n(r.cost_micros),0),average_latency_ms:lat.length?lat.reduce((a,b)=>a+b,0)/lat.length:0,success_rate:pct(completed,completed+failed),conversations:(convR.data??[]).length,assistant_messages:messages.filter(r=>s(r.role)==='assistant').length,summaries:(sumR.data??[]).length,sentiment_analyses:(sentR.data??[]).length,coaching_analyses:(coachR.data??[]).length,transcript_runs:(transR.data??[]).length,feature_metrics:dimension(usage,r=>s(r.feature)),prompt_metrics:dimension(promptByUsage,r=>s(r.prompt_key)),model_metrics:dimension(usage,r=>s(r.model)),provider_metrics:dimension(usage,r=>s(r.provider)),trend_metrics:trend(period,now,usage),captured_by:membership.user_id,metadata:{source:'flowtix-ai-analytics-v1',featureCount:new Set(usage.map(r=>s(r.feature))).size}};const {data,error:insertError}=await supabase.from('ai_analytics_snapshots').insert(payload).select('*').single();if(insertError)throw new Error(`Unable to save AI analytics snapshot: ${insertError.message}`);return map(data as StoredRow)}
const AI_ANALYTICS_FRESHNESS_MS=15*60*1000
function isFreshSnapshot(row:StoredRow|undefined):boolean{
 if(!row)return false
 const capturedAt=new Date(row.captured_at).getTime()
 return Number.isFinite(capturedAt)&&Date.now()-capturedAt<AI_ANALYTICS_FRESHNESS_MS
}
export async function getAIAnalyticsOverview(period:ReportRange):Promise<AIAnalyticsOverview>{const membership=await requirePermission('reports.view');const supabase=await createClient();const {data,error}=await supabase.from('ai_analytics_snapshots').select('*').eq('organization_id',membership.organization_id).eq('period',period).order('captured_at',{ascending:false}).limit(25);if(error)throw new Error(`Unable to load AI analytics: ${error.message}`);const stored=(data??[]) as StoredRow[];const snapshot=isFreshSnapshot(stored[0])?map(stored[0]):await collectAIAnalyticsSnapshot(period);const history=isFreshSnapshot(stored[0])?stored.map(row=>({id:row.id,period:row.period,periodStart:row.period_start,periodEnd:row.period_end,capturedAt:row.captured_at})):[{id:snapshot.id,period:snapshot.period,periodStart:snapshot.periodStart,periodEnd:snapshot.periodEnd,capturedAt:snapshot.capturedAt},...stored.map(row=>({id:row.id,period:row.period,periodStart:row.period_start,periodEnd:row.period_end,capturedAt:row.captured_at}))];return{snapshot,history}}
