export const guidePathMap: ReadonlyArray<{ prefix: string; slug: string; title: string }> = [
  { prefix: '/dashboard/settings/integrations', slug: 'integrations', title: 'Integrations' },
  { prefix: '/dashboard/campaign-analytics', slug: 'campaign-analytics', title: 'Campaign Analytics' },
  { prefix: '/dashboard/sales-analytics', slug: 'sales-analytics', title: 'Sales Analytics' },
  { prefix: '/dashboard/call-analytics', slug: 'call-analytics', title: 'Call Analytics' },
  { prefix: '/dashboard/agent-analytics', slug: 'agent-analytics', title: 'Agent Analytics' },
  { prefix: '/dashboard/ai-analytics', slug: 'ai-analytics', title: 'AI Analytics' },
  { prefix: '/dashboard/live-calls', slug: 'live-calls', title: 'Live Calls' },
  { prefix: '/dashboard/recordings', slug: 'recordings', title: 'Recordings' },
  { prefix: '/dashboard/transcripts', slug: 'transcripts', title: 'Transcripts' },
  { prefix: '/dashboard/communications', slug: 'email-sms', title: 'Email & SMS' },
  { prefix: '/dashboard/dashboards', slug: 'dashboards', title: 'Custom Dashboards' },
  { prefix: '/dashboard/attendance', slug: 'attendance', title: 'Time & Attendance' },
  { prefix: '/dashboard/organization', slug: 'organization', title: 'Organization' },
  { prefix: '/dashboard/sequences', slug: 'sequences', title: 'Sequences' },
  { prefix: '/dashboard/campaigns', slug: 'campaigns', title: 'Campaigns' },
  { prefix: '/dashboard/activities', slug: 'activities', title: 'Activities' },
  { prefix: '/dashboard/calendar', slug: 'calendar', title: 'Calendar' },
  { prefix: '/dashboard/templates', slug: 'templates', title: 'Templates' },
  { prefix: '/dashboard/snippets', slug: 'snippets', title: 'Snippets' },
  { prefix: '/dashboard/contacts', slug: 'contacts', title: 'Contacts' },
  { prefix: '/dashboard/companies', slug: 'companies', title: 'Companies' },
  { prefix: '/dashboard/pipelines', slug: 'pipelines', title: 'Pipelines' },
  { prefix: '/dashboard/timeline', slug: 'timeline', title: 'Timeline' },
  { prefix: '/dashboard/exports', slug: 'exports', title: 'Data Exports' },
  { prefix: '/dashboard/reports', slug: 'reports', title: 'Reports' },
  { prefix: '/dashboard/kpis', slug: 'kpi-engine', title: 'KPI Engine' },
  { prefix: '/dashboard/security', slug: 'security-center', title: 'Security Center' },
  { prefix: '/dashboard/roles', slug: 'roles-permissions', title: 'Roles & Permissions' },
  { prefix: '/dashboard/settings', slug: 'settings', title: 'Settings' },
  { prefix: '/dashboard/billing', slug: 'billing', title: 'Billing' },
  { prefix: '/dashboard/insights', slug: 'ai-insights', title: 'AI Insights' },
  { prefix: '/dashboard/ai', slug: 'ai-workspace', title: 'AI Workspace' },
  { prefix: '/dashboard/dialer', slug: 'dialer', title: 'Dialer' },
  { prefix: '/dashboard/calls', slug: 'calls', title: 'Calls' },
  { prefix: '/dashboard/files', slug: 'files', title: 'Files & attachments' },
  { prefix: '/dashboard/tags', slug: 'tags', title: 'Tags' },
  { prefix: '/dashboard/team', slug: 'team', title: 'Team' },
  { prefix: '/dashboard', slug: 'dashboard', title: 'Dashboard' },
]

export function getGuidePath(pathname: string) {
  return guidePathMap.find(({ prefix }) => pathname === prefix || pathname.startsWith(`${prefix}/`))
}
