import { Plug } from 'lucide-react'
import { canManageSettings, requireSettingsContext } from '@/lib/settings-context'
import { saveIntegration } from './actions'
const providers = ['twilio','telnyx','signalwire','plivo','openai','google-calendar','gmail','outlook','slack','zoom','microsoft-teams','n8n','zapier']
export default async function IntegrationsPage() {
 const { supabase, organizationId, role } = await requireSettingsContext(); const manageable=canManageSettings(role)
 const { data } = await supabase.from('organization_integrations').select('provider,enabled,status,config,updated_at').eq('organization_id',organizationId)
 const byProvider = new Map((data??[]).map(x=>[x.provider,x]))
 return <div className="space-y-8"><div><h1 className="text-3xl font-bold">Integrations</h1><p className="mt-2 text-muted-foreground">Configure telephony, AI, productivity, and automation connections.</p></div><div className="grid gap-4 lg:grid-cols-2">{providers.map(provider=>{const item=byProvider.get(provider); const config=(item?.config ?? {}) as Record<string,string>; return <form key={provider} action={saveIntegration} className="rounded-xl border border-border bg-card p-5"><input type="hidden" name="provider" value={provider}/><div className="flex items-start justify-between"><div className="flex gap-3"><Plug className="h-5 w-5 text-primary"/><div><h2 className="font-semibold capitalize">{provider.replaceAll('-',' ')}</h2><p className="text-sm text-muted-foreground">{item?.status ?? 'disconnected'}</p></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={item?.enabled} disabled={!manageable}/>Enabled</label></div><div className="mt-4 grid gap-3"><input name="account_label" defaultValue={config.account_label ?? ''} placeholder="Account label" disabled={!manageable} className="rounded-lg border bg-background px-3 py-2 text-sm"/><input name="webhook_url" defaultValue={config.webhook_url ?? ''} placeholder="Webhook or callback URL" disabled={!manageable} className="rounded-lg border bg-background px-3 py-2 text-sm"/></div>{manageable ? <button className="mt-4 rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-muted">Save integration</button>:null}</form>})}</div><p className="text-sm text-muted-foreground">OAuth authorization and provider secrets are completed in each provider dashboard. Do not store secret API tokens in these metadata fields.</p></div>
}
