import { requirePermission } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'
import type { TeamRole } from '@/lib/team'
import type { DashboardInput, DashboardKind, DashboardMetricValue, DashboardView, DashboardWidgetConfig, SavedDashboard } from './types'

type Row = Record<string, unknown>
const roles: TeamRole[] = ['owner','admin','manager','agent']
const kinds: DashboardKind[] = ['executive','sales','agent','campaign','ai','operations','telephony','custom']
const text=(v:unknown)=>typeof v==='string'?v:''
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{}
const widgets=(v:unknown):DashboardWidgetConfig[]=>Array.isArray(v)?v as DashboardWidgetConfig[]:[]
const roleList=(v:unknown):TeamRole[]=>Array.isArray(v)?v.filter((x):x is TeamRole=>roles.includes(x as TeamRole)):roles
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'dashboard'
function map(row:Row):SavedDashboard{return{id:text(row.id),organizationId:text(row.organization_id),name:text(row.name),slug:text(row.slug),description:row.description===null?null:text(row.description),kind:kinds.includes(row.kind as DashboardKind)?row.kind as DashboardKind:'custom',isDefault:Boolean(row.is_default),isSystem:Boolean(row.is_system),allowedRoles:roleList(row.allowed_roles),layout:widgets(row.layout),createdBy:text(row.created_by),createdAt:text(row.created_at),updatedAt:text(row.updated_at)}}
function canAccess(role:TeamRole,dashboard:SavedDashboard){return dashboard.allowedRoles.includes(role)}
async function latest(supabase:Awaited<ReturnType<typeof createClient>>,table:string,organizationId:string){const {data}=await supabase.from(table).select('*').eq('organization_id',organizationId).order('captured_at',{ascending:false}).limit(1).maybeSingle();return object(data)}
export async function listDashboards():Promise<SavedDashboard[]>{const membership=await requirePermission('reports.view');const supabase=await createClient();const {data,error}=await supabase.from('saved_dashboards').select('*').eq('organization_id',membership.organization_id).order('is_system',{ascending:false}).order('name');if(error)throw new Error(`Unable to load dashboards: ${error.message}`);return (data??[]).map(r=>map(r as Row)).filter(d=>canAccess(membership.role,d))}
export async function getDashboard(slug:string):Promise<DashboardView>{const membership=await requirePermission('reports.view');const supabase=await createClient();const {data,error}=await supabase.from('saved_dashboards').select('*').eq('organization_id',membership.organization_id).eq('slug',slug).maybeSingle();if(error)throw new Error(`Unable to load dashboard: ${error.message}`);if(!data)throw new Error('Dashboard not found');const dashboard=map(data as Row);if(!canAccess(membership.role,dashboard))throw new Error('Dashboard access denied');const [sales,calls,agents,campaigns,ai]=await Promise.all(['sales_analytics_snapshots','call_analytics_snapshots','agent_analytics_snapshots','campaign_analytics_snapshots','ai_analytics_snapshots'].map(t=>latest(supabase,t,membership.organization_id)));const {count:jobs}=await supabase.from('background_jobs').select('id',{count:'exact',head:true}).eq('organization_id',membership.organization_id).in('status',['pending','processing','retrying']);const metrics:Record<string,DashboardMetricValue>={
 'sales.pipeline_value':num(sales.pipeline_value), 'sales.won_revenue':num(sales.won_revenue), 'sales.win_rate':num(sales.win_rate), 'sales.open_opportunities':num(sales.open_opportunities),
 'calls.total':num(calls.total_calls), 'calls.answer_rate':num(calls.connect_rate), 'calls.average_duration':num(calls.average_duration_seconds), 'calls.failed':num(calls.failed_calls),
 'agents.active':num(agents.available_agents), 'agents.calls':num(agents.total_calls), 'agents.utilization':num(agents.average_productivity_score), 'agents.conversion_rate':num(agents.connect_rate),
 'campaigns.active':num(campaigns.active_campaigns), 'campaigns.enrollments':num(campaigns.enrollments), 'campaigns.conversion_rate':num(campaigns.conversion_rate), 'campaigns.roi':num(campaigns.roi),
 'ai.requests':num(ai.total_requests), 'ai.success_rate':num(ai.success_rate), 'ai.tokens':num(ai.total_tokens), 'ai.cost_micros':num(ai.cost_micros),
 'operations.pending_jobs':jobs??0, 'operations.snapshot_count':[sales,calls,agents,campaigns,ai].filter(v=>Object.keys(v).length>0).length,
 'telephony.calls':num(calls.total_calls), 'telephony.answer_rate':num(calls.connect_rate), 'telephony.failed':num(calls.failed_calls), 'telephony.duration':num(calls.average_duration_seconds),
 };return{dashboard,metrics}}
export async function createDashboard(input:DashboardInput):Promise<SavedDashboard>{const membership=await requirePermission('reports.view');const supabase=await createClient();const payload={organization_id:membership.organization_id,name:input.name.trim(),slug:slugify(input.slug||input.name),description:input.description??null,kind:input.kind??'custom',is_default:Boolean(input.isDefault),allowed_roles:input.allowedRoles?.length?input.allowedRoles:roles,layout:input.layout??[],created_by:membership.user_id};const {data,error}=await supabase.from('saved_dashboards').insert(payload).select('*').single();if(error)throw new Error(`Unable to create dashboard: ${error.message}`);return map(data as Row)}
export async function updateDashboard(id:string,input:DashboardInput):Promise<SavedDashboard>{const membership=await requirePermission('reports.view');const supabase=await createClient();const update:Record<string,unknown>={updated_at:new Date().toISOString()};if(input.name)update.name=input.name.trim();if(input.slug)update.slug=slugify(input.slug);if(input.description!==undefined)update.description=input.description;if(input.kind)update.kind=input.kind;if(input.isDefault!==undefined)update.is_default=input.isDefault;if(input.allowedRoles)update.allowed_roles=input.allowedRoles;if(input.layout)update.layout=input.layout;const {data,error}=await supabase.from('saved_dashboards').update(update).eq('id',id).eq('organization_id',membership.organization_id).eq('is_system',false).select('*').single();if(error)throw new Error(`Unable to update dashboard: ${error.message}`);return map(data as Row)}
export async function deleteDashboard(id:string):Promise<void>{const membership=await requirePermission('reports.view');const supabase=await createClient();const {error}=await supabase.from('saved_dashboards').delete().eq('id',id).eq('organization_id',membership.organization_id).eq('is_system',false);if(error)throw new Error(`Unable to delete dashboard: ${error.message}`)}
