begin;
create table if not exists public.security_threat_events(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,threat_type text not null,severity text not null check(severity in('low','medium','high','critical')),status text not null default 'open' check(status in('open','investigating','resolved','dismissed')),source text not null default 'application',ip_address inet,session_id uuid references public.user_sessions(id) on delete set null,device_id uuid references public.user_devices(id) on delete set null,description text not null,indicators jsonb not null default '{}'::jsonb,detected_at timestamptz not null default now(),resolved_at timestamptz,resolved_by uuid references auth.users(id) on delete set null,resolution_notes text);
create index if not exists security_threat_events_org_status_idx on public.security_threat_events(organization_id,status,severity,detected_at desc);
alter table public.security_threat_events enable row level security;
create policy "admins read threats" on public.security_threat_events for select using(exists(select 1 from public.organization_members m where m.organization_id=security_threat_events.organization_id and m.user_id=auth.uid() and m.role in('owner','admin')) or user_id=auth.uid());
create policy "admins update threats" on public.security_threat_events for update using(exists(select 1 from public.organization_members m where m.organization_id=security_threat_events.organization_id and m.user_id=auth.uid() and m.role in('owner','admin'))) with check(exists(select 1 from public.organization_members m where m.organization_id=security_threat_events.organization_id and m.user_id=auth.uid() and m.role in('owner','admin')));
create or replace function public.detect_security_threats() returns integer language plpgsql security definer set search_path=public as $$ declare n integer:=0; begin
insert into public.security_threat_events(organization_id,user_id,threat_type,severity,source,ip_address,description,indicators)
select s.organization_id,s.user_id,'rapid_ip_change','high','session_monitor',s.ip_address,'Rapid IP change detected for an active account.',jsonb_build_object('session_id',s.id)
from public.user_sessions s join public.user_sessions p on p.user_id=s.user_id and p.id<>s.id and p.last_seen_at>s.last_seen_at-interval '15 minutes' and p.last_seen_at<=s.last_seen_at and p.ip_address is distinct from s.ip_address
where s.last_seen_at>now()-interval '20 minutes' and not exists(select 1 from public.security_threat_events t where t.user_id=s.user_id and t.threat_type='rapid_ip_change' and t.detected_at>now()-interval '1 hour'); get diagnostics n=row_count; return n; end $$;
revoke all on function public.detect_security_threats() from public; grant execute on function public.detect_security_threats() to service_role;
do $$ begin if exists(select 1 from pg_extension where extname='pg_cron') then perform cron.schedule('flowtix-threat-detection','*/10 * * * *',$cron$select public.detect_security_threats();$cron$); end if; exception when others then null; end $$;
commit;
