-- Flowtix Automation 1.8
-- Register provider-neutral post-call communication sources.
--
-- Email generated by post-call automation uses `post_call_email`.
-- Automation 1.9 will use the already-reserved `post_call_sms` source.
-- Keeping separate source values lets both channels share the same durable
-- post-call dispatch job ID while preserving the existing
-- (organization_id, source, source_record_id) idempotency index.

begin;

alter table public.communication_messages
  drop constraint if exists communication_messages_source_check;

alter table public.communication_messages
  add constraint communication_messages_source_check
  check (
    source in (
      'manual',
      'sequence',
      'campaign',
      'api',
      'system',
      'post_call_email',
      'post_call_sms'
    )
  );

comment on column public.communication_messages.source is
  'Origin of the communication. post_call_email and post_call_sms are durable automated follow-ups created from canonical completed-call dispatch jobs.';

commit;
