begin;
create table if not exists public.permission_catalog(permission_key text primary key,category text not null,display_name text not null,description text,is_system boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.organization_role_permissions(role_id uuid not null references public.organization_roles(id) on delete cascade,permission_key text not null references public.permission_catalog(permission_key) on delete cascade,granted_by uuid references auth.users(id) on delete set null,granted_at timestamptz not null default now(),primary key(role_id,permission_key));
alter table public.permission_catalog enable row level security; alter table public.organization_role_permissions enable row level security;
create policy "authenticated read permission catalog" on public.permission_catalog for select to authenticated using(true);
create policy "members read role permissions" on public.organization_role_permissions for select using(exists(select 1 from public.organization_roles r join public.organization_members m on m.organization_id=r.organization_id where r.id=organization_role_permissions.role_id and m.user_id=auth.uid()));
insert into public.permission_catalog(permission_key,category,display_name,description) values
('organization.view','organization','View organization','View organization information'),('organization.update','organization','Update organization','Change organization configuration'),('team.view','team','View team','View organization members and teams'),('team.invite','team','Invite members','Invite new organization members'),('team.update_roles','team','Manage roles','Assign roles and permissions'),('team.remove_members','team','Remove members','Deactivate organization memberships'),('settings.view','platform','View settings','View platform administration settings'),('settings.manage','platform','Manage settings','Manage platform administration settings'),('jobs.view','operations','View jobs','View background job health'),('jobs.manage','operations','Manage jobs','Manage background job operations'),('audit_logs.view','security','View audit logs','View security and audit events') on conflict(permission_key) do update set category=excluded.category,display_name=excluded.display_name,description=excluded.description;
commit;
