begin;

alter table public.ai_task_suggestions
  add column if not exists transcript_id uuid references public.transcripts(id) on delete set null,
  add column if not exists category text,
  add column if not exists suggested_due_at timestamptz,
  add column if not exists rationale text,
  add column if not exists status text,
  add column if not exists accepted_by uuid references auth.users(id) on delete set null,
  add column if not exists accepted_task_id uuid references public.contact_tasks(id) on delete set null,
  add column if not exists dismissed_at timestamptz,
  add column if not exists dismissed_by uuid references auth.users(id) on delete set null,
  add column if not exists source_hash text,
  add column if not exists generation_key text,
  add column if not exists generation_position integer,
  add column if not exists provider text,
  add column if not exists model text,
  add column if not exists prompt_key text,
  add column if not exists prompt_version integer,
  add column if not exists provider_request_id text,
  add column if not exists input_tokens integer,
  add column if not exists output_tokens integer,
  add column if not exists latency_ms integer,
  add column if not exists metadata jsonb;

update public.ai_task_suggestions
set
  category = coalesce(category, 'follow_up'),
  suggested_due_at = coalesce(suggested_due_at, created_at + make_interval(days => due_in_days)),
  rationale = coalesce(rationale, 'Generated by the legacy AI task suggestion workflow.'),
  status = coalesce(status, case when accepted_at is null then 'pending' else 'accepted' end),
  source_hash = coalesce(source_hash, encode(digest(id::text, 'sha256'), 'hex')),
  generation_key = coalesce(generation_key, encode(digest(organization_id::text || ':' || id::text, 'sha256'), 'hex')),
  generation_position = coalesce(generation_position, 1),
  provider = coalesce(provider, 'legacy'),
  prompt_key = coalesce(prompt_key, 'tasks.suggest'),
  prompt_version = coalesce(prompt_version, 1),
  metadata = coalesce(metadata, '{}'::jsonb);

alter table public.ai_task_suggestions
  alter column category set not null,
  alter column suggested_due_at set not null,
  alter column rationale set not null,
  alter column status set not null,
  alter column source_hash set not null,
  alter column generation_key set not null,
  alter column generation_position set not null,
  alter column provider set not null,
  alter column prompt_key set not null,
  alter column prompt_version set not null,
  alter column metadata set not null,
  alter column metadata set default '{}'::jsonb;

alter table public.ai_task_suggestions
  drop constraint if exists ai_task_suggestions_category_check,
  add constraint ai_task_suggestions_category_check
    check (category in ('follow_up','call','email','meeting','research','internal')),
  drop constraint if exists ai_task_suggestions_status_check,
  add constraint ai_task_suggestions_status_check
    check (status in ('pending','accepted','dismissed')),
  drop constraint if exists ai_task_suggestions_generation_position_check,
  add constraint ai_task_suggestions_generation_position_check
    check (generation_position between 1 and 8),
  drop constraint if exists ai_task_suggestions_prompt_version_check,
  add constraint ai_task_suggestions_prompt_version_check
    check (prompt_version > 0),
  drop constraint if exists ai_task_suggestions_token_check,
  add constraint ai_task_suggestions_token_check
    check (
      (input_tokens is null or input_tokens >= 0)
      and (output_tokens is null or output_tokens >= 0)
      and (latency_ms is null or latency_ms >= 0)
    );

create unique index if not exists ai_task_suggestions_generation_position_uidx
  on public.ai_task_suggestions (organization_id, generation_key, generation_position);
create index if not exists ai_task_suggestions_status_created_idx
  on public.ai_task_suggestions (organization_id, status, created_at desc);
create index if not exists ai_task_suggestions_contact_status_idx
  on public.ai_task_suggestions (organization_id, contact_id, status)
  where contact_id is not null;
create index if not exists ai_task_suggestions_call_status_idx
  on public.ai_task_suggestions (organization_id, call_id, status)
  where call_id is not null;
create index if not exists ai_task_suggestions_transcript_idx
  on public.ai_task_suggestions (organization_id, transcript_id, created_at desc)
  where transcript_id is not null;

create or replace function public.accept_ai_task_suggestion(
  target_organization_id uuid,
  target_suggestion_id uuid,
  target_assigned_to uuid default null
)
returns table(task_id uuid, reused boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  suggestion public.ai_task_suggestions%rowtype;
  target_membership_id uuid;
  created_task_id uuid;
begin
  if actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.organization_members member
    where member.organization_id = target_organization_id
      and member.user_id = actor_id
      and member.status = 'active'
  ) then
    raise exception 'Active organization membership is required.' using errcode = '42501';
  end if;

  select * into suggestion
  from public.ai_task_suggestions item
  where item.id = target_suggestion_id
    and item.organization_id = target_organization_id
  for update;

  if not found then raise exception 'AI task suggestion was not found.'; end if;
  if suggestion.status = 'dismissed' then raise exception 'Dismissed suggestions cannot be accepted.'; end if;
  if suggestion.status = 'accepted' and suggestion.accepted_task_id is not null then
    return query select suggestion.accepted_task_id, true;
    return;
  end if;

  if target_assigned_to is not null then
    select member.id into target_membership_id
    from public.organization_members member
    where member.organization_id = target_organization_id
      and member.user_id = target_assigned_to
      and member.status = 'active'
    limit 1;
    if target_membership_id is null then
      raise exception 'The selected assignee is not an active organization member.';
    end if;
  else
    target_assigned_to := actor_id;
    select member.id into target_membership_id
    from public.organization_members member
    where member.organization_id = target_organization_id
      and member.user_id = actor_id
      and member.status = 'active'
    limit 1;
  end if;

  insert into public.contact_tasks (
    organization_id, contact_id, title, description, due_at, status, priority,
    assigned_to, owner_membership_id, created_by, completed_at
  ) values (
    target_organization_id,
    suggestion.contact_id,
    suggestion.title,
    suggestion.description,
    suggestion.suggested_due_at,
    'pending',
    suggestion.priority,
    target_assigned_to,
    target_membership_id,
    actor_id,
    null
  ) returning id into created_task_id;

  update public.ai_task_suggestions
  set status = 'accepted', accepted_at = now(), accepted_by = actor_id,
      accepted_task_id = created_task_id, dismissed_at = null, dismissed_by = null
  where id = suggestion.id;

  return query select created_task_id, false;
end;
$$;

revoke all on function public.accept_ai_task_suggestion(uuid, uuid, uuid) from public;
grant execute on function public.accept_ai_task_suggestion(uuid, uuid, uuid) to authenticated;

alter table public.ai_task_suggestions enable row level security;
drop policy if exists ai_task_suggestions_tenant_access on public.ai_task_suggestions;
drop policy if exists ai_task_suggestions_select_member on public.ai_task_suggestions;
create policy ai_task_suggestions_select_member on public.ai_task_suggestions
for select to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists ai_task_suggestions_insert_member on public.ai_task_suggestions;
create policy ai_task_suggestions_insert_member on public.ai_task_suggestions
for insert to authenticated
with check (
  created_by = auth.uid()
  and public.is_organization_member(organization_id)
  and (contact_id is null or exists (select 1 from public.contacts c where c.id = contact_id and c.organization_id = organization_id))
  and (call_id is null or exists (select 1 from public.calls c where c.id = call_id and c.organization_id = organization_id))
  and (transcript_id is null or exists (select 1 from public.transcripts t where t.id = transcript_id and t.organization_id = organization_id))
);

drop policy if exists ai_task_suggestions_update_member on public.ai_task_suggestions;
create policy ai_task_suggestions_update_member on public.ai_task_suggestions
for update to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

drop policy if exists ai_task_suggestions_delete_member on public.ai_task_suggestions;
create policy ai_task_suggestions_delete_member on public.ai_task_suggestions
for delete to authenticated
using (created_by = auth.uid() or public.can_manage_organization_assignments(organization_id));

revoke all on public.ai_task_suggestions from anon;
grant select, insert, update, delete on public.ai_task_suggestions to authenticated;

commit;
